apiVersion: v1
kind: Service
metadata:
  name: sdb-kafka-github-service
  namespace: sdb-prod-v4
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: sdb-kafka-github-service